server:
  port: 8020
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1994Manish/-spring-cloud-config-repository.git
          #user: xxx
          #password: T
          search-paths:
          - zuul,loan,eureka
          force-pull: true
          